### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by ghost** [NateXVI/Online-Flappy-Bird#1]
How can I clear Leaderboard names? as I want to start from fresh.
or
Please share Leaderboard file that you saved on cloud.

**Comment by NateXVI** [comment]
The leaderboard names are stored on a PostgreSQL database hosted on Heroku. To clear the names you need to erase all the entries in the database table that stores all the high scores. 

If you are starting from scratch you will need to have your own database. [Heroku](https://www.heroku.com/postgres) has a free tier for hosting a PostgreSQL database, or you can [download](https://www.postgresql.org/download/) and run the database on your own computer.
